name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite UTC
  workflow_dispatch: # Para rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: galaxy76709
          outputs: dist/github-snake.svg

      - name: Verificar se a cobrinha foi gerada
        run: |
          echo "Verificando se o arquivo foi gerado"
          ls -al dist

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
